name: todokill
description: "A simple ToDo application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  grpc: ^4.1.0
  protobuf: ^4.1.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  protoc_plugin: ^22.0.0

flutter:
  uses-material-design: true